### ISSUE TITLE
Black screen after flashing the unit with uf2

### ISSUE THREAD

**Issue by sudo-lupus666** [tzmwx/USBTO3DO-FZ10#1]
I was able, through Linux Ubuntu, to compile firmware using cmake and Mr. François' source code from his SataTo3DO project, as the instructions of this project say. 

I reached mr François to ask him for permission to assemble some units for me and for some friends and I got his permission. 

I flashed my FZ-10  pico ode with my uf2 file, but all I got was a black screen, after turning on my 3do. It looked like it was reading data from the USB flash drive, but the menu didn't start. 

I don't think it's necessary to show the messages between me and Mr. François, but if the developer of this project thinks it's necessary to show them in order to help me with my build, I got them and I can show them. 

I think I've got a problem with the uf2 file, but I don't understand why, if I did like the instructions said. 

Thank you all for your help :D ![image](https://github.com/tzmwx/USBTO3DO-FZ10/assets/83513847/dd240a77-1cd6-4c23-8bab-7eb0926e1cb0)

![image](https://github.com/tzmwx/USBTO3DO-FZ10/assets/83513847/1565bb38-1d4f-44c9-83a1-9ad2342d7bab)

![image](https://github.com/tzmwx/USBTO3DO-FZ10/assets/83513847/390f67ff-dfc0-4abb-bd5a-86aadb3c581c)

**Comment by tzmwx** [comment]
Source code has been updated on April 25, you need to recompile according to his updated content to get the uf2 file. Or you can contact me on Twitter.

**Comment by sudo-lupus666** [comment]
> Source code has been updated on April 25, you need to recompile according to his updated content to get the uf2 file. Or you can contact me on Twitter.

Ty for your answer! I recompiled using the source code available at the page of the project, but it didn’t work whatsoever. Can you email me the new uf2 file for the fz10? Ty!

lupus123@outlook.com.br

**Comment by tzmwx** [comment]
Twitter：@TZMWXdiyer

**Comment by sudo-lupus666** [comment]
Will do!

**Comment by Aisflou** [comment]
Then, compiling the lastest files from the Francois github doesnt work?

**Comment by sudo-lupus666** [comment]
It seens there is a problem with my install. I’m checking everything again to find out what it is. The uf2 seens to be fine.

**Comment by jpjodoin** [comment]
@sudo-lupus666 : Did you ever figure it out ? I've just finished assembling this mod and I'm having the same issue. I see the 3DO logo and after that the screen goes black. I see the led on my USB key flash for a few seconds and nothing. I've built and flashed the latest uf2 from François repo on the rp2040 and I've plugged in a usb memory stick with the boot.flash from fixel and an ISO.

Now, I'll recheck every connection from my PCB/install to be sure, but if you found your issue, please let me know!
