### ISSUE TITLE
BOM Clarification

### ISSUE THREAD

**Issue by rain2usa** [tzmwx/USBTO3DO-FZ10#2]
Hello.  I am gathering the parts for this build and am confused by your BOM saying all the Capacitors are not required to be installed but the final, completed picture of the board has 1 electrolytic capacitor on C2.  Can you confirm if this is really needed or not?

**Comment by rain2usa** [comment]
Also need clarification on the resistors and Transistor on R4/R5, Q2.  What are these as they are not listed in the Readme?

**Comment by tzmwx** [comment]
1.所有电容不是必须的，可以全部不安装
2.如果你要在模块上建立一个CD盖子开关换盘功能，你需要增加R2 4.7K，R3 10K，Q1 9014(或其他NPN三极管） (SMD0603或直插)

**Comment by tzmwx** [comment]
1.所有电容不是必须的，可以全部不安装
2.20230501版本的PCB已经取消了R4/R5/Q2

**Comment by rain2usa** [comment]
Thank you.  I was looking at the install photos and didn't notice the Final PCB removed those.  That makes it a little easier to put together now.  I have ordered the BOM.

**Comment by rain2usa** [comment]
Everything is working now.  BOM I ordered seems to be correct.  Thank you for the help.

**Comment by rain2usa** [comment]
Reopening issue just to post photos of the completed MOD.  Test Game functionality and Audio CD functionality to put the clock mod to the test.  It does work, but required an img+cue rip for me.  I couldn't get any other audio image to work under the current boot firmware.  My menu is a little shifted but that's due to the RGB Mod.  I haven't tweaked the dipswitches to correct it yet.  As far as the mod, it is challenging so here are some tips.
1) I had to use sub-30awg wires for the main wiring to fit into the vias.  30awg solid core wires work well for wiring everything else (like Cover, Read, Clock).  
2) Gerber PCB is different from the Photos of the PCB you see in the instructions.  Gerber PCB will match the Readme file, so be aware of that.
3) I found the oscillator on aliexpress. Had no luck on Digikey or Mouser in the States. 
4) if your Pi Pico has a microUSB port on it, I highly recommend programming it BEFORE you solder it on cause access to it will be limited.  I had to cut the rubber on the connector on mine to do the initial programming (but reality is if you plan on using the USB Extension as described in the instructions, the above won't matter.  You can use the USB extension to program the Pi). 
5) For the LED Read MOD, you do lift the Q410 pin and then solder the wire to the lifted pin.
6) For Clock mod, you do lift pin 84, then wire it up as shown in the audioCD folder.  
7) As the instruction say, if you do use the USB Extension, make sure you solder the two points on the bottom of the Pi to the PCB on the bottom well before you try mounting.  You won't have access to this after you solder it on.
8) Use an appropriately sized heat shrink tube to gather the wire strands into two sets, then feed it through the PCB.  Much easier than to try to feed each strand through the openings. 
9) It is possible to mount this outside the case without cutting anything.  I used a standard USB A cable soldered to the board, then a USB 2.0 (not 3.0 or above as all of them failed for me) MicroSD card reader, then a MicroSD Extension as you see in one of the photos below.  This works really nice and there is a lot of open space in the case to house this without any pressure. 

![PCB Complete](https://github.com/tzmwx/USBTO3DO-FZ10/assets/107739348/0886f35e-1b74-4ec5-9667-d65292b3bcf4)
![Main Board Wired](https://github.com/tzmwx/USBTO3DO-FZ10/assets/107739348/e619852c-a223-466f-9d8e-6e03351d2a50)
![MOD Complete](https://github.com/tzmwx/USBTO3DO-FZ10/assets/107739348/c6f5c646-a6c3-4cb2-9457-5e403d61b10f)
![Working System](https://github.com/tzmwx/USBTO3DO-FZ10/assets/107739348/eb94b7c6-6c4e-4b7f-bfd1-c879a9b95b7a)
![ODE Working](https://github.com/tzmwx/USBTO3DO-FZ10/assets/107739348/137c204c-7e3e-4b31-a486-431f4b87ce6e)
![External MicroSD](https://github.com/tzmwx/USBTO3DO-FZ10/assets/107739348/50015900-f9ac-4ea6-aa7b-d924f2fc4e27)
![Audio CD MOD](https://github.com/tzmwx/USBTO3DO-FZ10/assets/107739348/9b283ba7-fe59-488d-a5bb-10d3cf9e81e3)
